"""
config.py
---------
Bucket anchor keywords for fuzzy heading assignment.

Each bucket has a list of representative phrases that describe what kind of
content belongs there. When a heading is detected in a PDF, it is scored
against all anchors across all buckets — the bucket with the highest
similarity wins, provided it clears the MATCH_THRESHOLD.

  - MATCH_THRESHOLD: lower (e.g. 0.25) = more forgiving, fewer misc sections.
    Raise (e.g. 0.5) if unrelated headings are being misclassified.
  - Add anchors freely — more anchors = better coverage, no ordering needed.
  - Anchors should be lowercase and use natural phrasing.
  - Prefer specific phrases over single words where possible, as they
    produce more discriminating matches.
"""

# ── Similarity threshold ──────────────────────────────────────────────────────
# Headings scoring below this against all buckets are assigned to misc.
# Range: 0.0 (accept everything) to 1.0 (exact match only).
MATCH_THRESHOLD = 0.35

# ── Bucket anchor lists ───────────────────────────────────────────────────────

BUCKET_ANCHORS = {
    "abstract": [
        "abstract",
        "introduction",
        "background",
        "overview",
        "study aims",
        "research aims",
        "objectives of this study",
        "research objectives",
        "study overview",
        "research context",
        "motivation",
        "research motivation",
        "background and motivation",
        "research background",
        "scope",
        "summary",
        "perspective",
        "open peer review",
        "reviewer reports",
        "problem statement",
        "research questions",
        "contribution",
        "study background",
        "context and motivation",
    ],

    "data_description": [
        "data",
        "dataset",
        "datasets",
        "data records",
        "description of data",
        "data description",
        "data sources",
        "data collection",
        "data acquisition",
        "acquisition",
        "variable definitions",
        "variables",
        "features",
        "schema",
        "attributes",
        "field definitions",
        "construction of samples",
        "sample construction",
        "study population",
        "cohort",
        "usage notes",
        "data availability",
        "provenance",
        "data and methods",
        "corpus",
        "ground truth",
        "annotation",
        "labelling",
        "survey design",
    ],

    "methods": [
        "methods",
        "methodology",
        "methods and materials",
        "materials and methods",
        "approach",
        "experimental setup",
        "experiments",
        "experimental design",
        "research design",
        "research design and analysis",
        "data cleaning",
        "data preprocessing",
        "data preparation",
        "preprocessing pipeline",
        "data processing pipeline",
        "data-processing pipeline",
        "data quality issues",
        "data-quality issues",
        "quality issues",
        "data quality",
        "basic data cleaning process",
        "pre-processed before sentiment analysis",
        "automated approaches to handling missing data",
        "outlier detection and removal",
        "outlier detection",
        "noise reduction",
        "feature selection and dimensionality reduction",
        "feature selection",
        "feature engineering",
        "imputation",
        "missing data",
        "normalisation",
        "standardisation",
        "transformation",
        "model validation",
        "evaluation",
        "evaluation results of classifiers",
        "evaluation of r squared",
        "natural language processing",
        "nlp",
        "algorithms",
        "detection",
        "inference",
        "modifications",
        "augmenting",
        "data augmentation",
        "selection criteria",
        "sensitive attribute labelling",
        "procurement of sensitive attributes",
        "data perturbation",
        "quantitative analysis",
        "statistical analysis",
        "analysis at the bed level",
        "physician fixed effects",
        "correction strategies",
        "sensitivity analysis",
        "research results and interpretation",
        "results",
        "findings",
        "implementation",
        "procedure",
        "workflow",
        "pipeline",
        "reweighting",
        "sampling",
        "aggregation",
        "table summary of robustness tests",
        "robustness tests",
        "study design",
        "analytical approach",
        "analytical framework",
        "research approach",
        "design and analysis",
        "study design and analysis",
        "analytical methods",
    ],

    "limitations": [
        "limitations",
        "limitation",
        "limitations of current ai models",
        "limitations of popular algorithmic fairness datasets",
        "challenges and limitations of ai in data preprocessing",
        "challenges and limitations",
        "challenges",
        "biases",
        "bias",
        "data quality issues",
        "data-quality issues",
        "transparency",
        "interpretability and transparency of ai algorithms",
        "interpretability",
        "issues",
        "known issues",
        "shortcomings",
        "constraints",
        "caveats",
        "threats to validity",
        "discussion",
        "conclusions and recommendations",
        "conclusion",
        "future work",
        "open questions",
        "ethical considerations",
        "privacy",
        "fairness",
        "generalisability",
        "representativeness",
        "selection bias",
        "missing data limitations",
    ],
}